### ISSUE TITLE
Unable to "Pair with Teams"

### ISSUE THREAD

**Issue by cvanover7** [jimmyeao/TEAMS2HA#21]
"Pair with Teams" provides no pairing request in Teams. Teams status remains "Disconnected" and MQTT Status is "Connected". Note: This machine is locked down with no admin rights.

Teams2HA version: 1.1.0.242
 Teams version 23335.232.2637.4844.
The client version is 49/23113028724.

This section of the logs just repeats:
2024-01-25 11:47:18.509 -06:00 [DBG] Attempting reconnection, try 1 of 5
2024-01-25 11:47:22.595 -06:00 [ERR] ConnectAsync: Error connecting to WebSocket
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:8124)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at TEAMS2HA.API.WebSocketClient.ConnectAsync(Uri uri) in C:\Users\jimmy\source\repos\TEAMS2HA\API\Teams.cs:line 125
2024-01-25 11:47:22.597 -06:00 [DBG] Attempting reconnection, try 1 of 5

**Comment by cvanover7** [comment]
Fixed. You have to go "Enable API" in teams in order.

**Comment by jimmyeao** [comment]
Glad you got it sorted, and thanks for the sponsorship, it’s really appreciated :)

**Comment by cvanover7** [comment]
You’re welcome. I’ve been searching how and low for this and found about
1/2 dozen others that had similar functionality but always ran into one
issue or another but got yours running with almost no effort. (I had the
‘manage API’ issue because it was a new laptop and I hadn’t enable it yet).

One feature to consider (if possible) would be a standalone EXE that would
not require an installation or special privileges, just run it from a temp
or home directory. An IT Admin installed this one for me (as a favor) but I
think auto updates will fail due to privledges.

Thanks again.

**Comment by Valdorama** [comment]
Been running this on work laptop for ages, then had to install on a replacement laptop. Could not get it to connect - searched the closed issues and finally found this. 'Enable API' did the trick. I think it would be worthwhile to mention this on the main README. 

Thanks for this project, it's tremendously useful.
